// const sampleListings = [
//   {
//     title: "Cozy Beachfront Cottage",
//     description:
//       "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1500,
//     location: "Malibu",
//     country: "United States",
//   },
//   {
//     title: "Modern Loft in Downtown",
//     description:
//       "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1200,
//     location: "New York City",
//     country: "United States",
//   },
//   {
//     title: "Mountain Retreat",
//     description:
//       "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1000,
//     location: "Aspen",
//     country: "United States",
//   },
//   {
//     title: "Historic Villa in Tuscany",
//     description:
//       "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2500,
//     location: "Florence",
//     country: "Italy",
//   },
//   {
//     title: "Secluded Treehouse Getaway",
//     description:
//       "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 800,
//     location: "Portland",
//     country: "United States",
//   },
//   {
//     title: "Beachfront Paradise",
//     description:
//       "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2000,
//     location: "Cancun",
//     country: "Mexico",
//   },
//   {
//     title: "Rustic Cabin by the Lake",
//     description:
//       "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 900,
//     location: "Lake Tahoe",
//     country: "United States",
//   },
//   {
//     title: "Luxury Penthouse with City Views",
//     description:
//       "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 3500,
//     location: "Los Angeles",
//     country: "United States",
//   },
//   {
//     title: "Ski-In/Ski-Out Chalet",
//     description:
//       "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 3000,
//     location: "Verbier",
//     country: "Switzerland",
//   },
//   {
//     title: "Safari Lodge in the Serengeti",
//     description:
//       "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4000,
//     location: "Serengeti National Park",
//     country: "Tanzania",
//   },
//   {
//     title: "Historic Canal House",
//     description:
//       "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1800,
//     location: "Amsterdam",
//     country: "Netherlands",
//   },
//   {
//     title: "Private Island Retreat",
//     description:
//       "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 10000,
//     location: "Fiji",
//     country: "Fiji",
//   },
//   {
//     title: "Charming Cottage in the Cotswolds",
//     description:
//       "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1200,
//     location: "Cotswolds",
//     country: "United Kingdom",
//   },
//   {
//     title: "Historic Brownstone in Boston",
//     description:
//       "Step back in time in this elegant historic brownstone located in the heart of Boston.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2200,
//     location: "Boston",
//     country: "United States",
//   },
//   {
//     title: "Beachfront Bungalow in Bali",
//     description:
//       "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1800,
//     location: "Bali",
//     country: "Indonesia",
//   },
//   {
//     title: "Mountain View Cabin in Banff",
//     description:
//       "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1500,
//     location: "Banff",
//     country: "Canada",
//   },
//   {
//     title: "Art Deco Apartment in Miami",
//     description:
//       "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
//     image: {
//       filename: "listingimage",
//       url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1600,
//     location: "Miami",
//     country: "United States",
//   },
//   {
//     title: "Tropical Villa in Phuket",
//     description:
//       "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 3000,
//     location: "Phuket",
//     country: "Thailand",
//   },
//   {
//     title: "Historic Castle in Scotland",
//     description:
//       "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4000,
//     location: "Scottish Highlands",
//     country: "United Kingdom",
//   },
//   {
//     title: "Desert Oasis in Dubai",
//     description:
//       "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 5000,
//     location: "Dubai",
//     country: "United Arab Emirates",
//   },
//   {
//     title: "Rustic Log Cabin in Montana",
//     description:
//       "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1100,
//     location: "Montana",
//     country: "United States",
//   },
//   {
//     title: "Beachfront Villa in Greece",
//     description:
//       "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2500,
//     location: "Mykonos",
//     country: "Greece",
//   },
//   {
//     title: "Eco-Friendly Treehouse Retreat",
//     description:
//       "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 750,
//     location: "Costa Rica",
//     country: "Costa Rica",
//   },
//   {
//     title: "Historic Cottage in Charleston",
//     description:
//       "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1600,
//     location: "Charleston",
//     country: "United States",
//   },
//   {
//     title: "Modern Apartment in Tokyo",
//     description:
//       "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 2000,
//     location: "Tokyo",
//     country: "Japan",
//   },
//   {
//     title: "Lakefront Cabin in New Hampshire",
//     description:
//       "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1200,
//     location: "New Hampshire",
//     country: "United States",
//   },
//   {
//     title: "Luxury Villa in the Maldives",
//     description:
//       "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 6000,
//     location: "Maldives",
//     country: "Maldives",
//   },
//   {
//     title: "Ski Chalet in Aspen",
//     description:
//       "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 4000,
//     location: "Aspen",
//     country: "United States",
//   },
//   {
//     title: "Secluded Beach House in Costa Rica",
//     description:
//       "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
//     image: {
//       filename: "listingimage",
//       url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
//     },
//     price: 1800,
//     location: "Costa Rica",
//     country: "Costa Rica",
//   },
// ];

// module.exports = { data: sampleListings };

// module.exports.data = [
//   {
//     title: "Beachside Villa",
//     description: "A beautiful villa near the beach.",
//     image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
//     price: 3000,
//     location: "Goa",
//     country: "India",
//   },
//   {
//     title: "Mountain Cabin",
//     description: "Peaceful place in the hills.",
//     image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
//     price: 1500,
//     location: "Manali",
//     country: "India",
//   },
//     {
//       title: "Lakefront Cottage",
//       description: "A cozy cottage by the lake.",
//       image: "https://images.unsplash.com/photo-1529262104063-8cb5807be81d?auto=format&fit=crop&w=800&q=60",
//       price: 2000,
//       location: "Nainital",
//       country: "India",
//     },
//     {
//       title: "Luxury Penthouse",
//       description: "A modern penthouse with stunning city views.",
//       image: "https://images.unsplash.com/photo-1587620974582-5e5b1c6c6e8d?auto=format&fit=crop&w=800&q=60",
//       price: 5000,
//       location: "Mumbai",
//       country: "India",
//     },
//     {
//       title: "Countryside Farmhouse",
//       description: "Rustic charm in the heart of nature.",
//       image: "https://images.unsplash.com/photo-1583175202342-41004ea90e45?auto=format&fit=crop&w=800&q=60",
//       price: 2500,
//       location: "Pondicherry",
//       country: "India",
//     },
//     {
//       title: "Desert Retreat",
//       description: "A peaceful retreat in the desert.",
//       image: "https://images.unsplash.com/photo-1560286705-6f512ac5851d?auto=format&fit=crop&w=800&q=60",
//       price: 1800,
//       location: "Rajasthan",
//       country: "India",
//     },
//     {
//       title: "Forest Lodge",
//       description: "Secluded lodge surrounded by forest.",
//       image: "https://images.unsplash.com/photo-1485858454438-38e1ed6fa5e0?auto=format&fit=crop&w=800&q=60",
//       price: 2200,
//       location: "Coorg",
//       country: "India",
//     },
//     {
//       title: "Seaside Resort",
//       description: "Luxury resort with ocean views.",
//       image: "https://images.unsplash.com/photo-1534920127346-433c9039e6b7?auto=format&fit=crop&w=800&q=60",
//       price: 3500,
//       location: "Kerala",
//       country: "India",
//     },
//     {
//       title: "Skyline Loft",
//       description: "Trendy loft with skyline views.",
//       image: "https://images.unsplash.com/photo-1599048761290-366e8a61c1a2?auto=format&fit=crop&w=800&q=60",
//       price: 4000,
//       location: "Bengaluru",
//       country: "India",
//     },
//     {
//       title: "Riverbank Bungalow",
//       description: "A serene bungalow by the river.",
//       image: "https://images.unsplash.com/photo-1534276172004-81931d4d3f4e?auto=format&fit=crop&w=800&q=60",
//       price: 2800,
//       location: "Rishikesh",
//       country: "India",
//     },
//     {
//       title: "Hilltop Villa",
//       description: "A luxury villa with panoramic views.",
//       image: "https://images.unsplash.com/photo-1534920127346-433c9039e6b7?auto=format&fit=crop&w=800&q=60",
//       price: 4500,
//       location: "Shimla",
//       country: "India",
//     },
//     {
//       title: "Urban Studio",
//       description: "Modern studio in the heart of the city.",
//       image: "https://images.unsplash.com/photo-1600823856711-d9b6f97ff8b9?auto=format&fit=crop&w=800&q=60",
//       price: 1800,
//       location: "Delhi",
//       country: "India",
//     },
//     {
//       title: "Beachfront Mansion",
//       description: "Opulent mansion on the beach.",
//       image: "https://images.unsplash.com/photo-1573544131244-df078fd58f9b?auto=format&fit=crop&w=800&q=60",
//       price: 6000,
//       location: "Goa",
//       country: "India",
//     },
//     {
//       title: "Island Getaway",
//       description: "Private island with stunning views.",
//       image: "https://images.unsplash.com/photo-1604017995789-d9b7edb3bbf9?auto=format&fit=crop&w=800&q=60",
//       price: 7000,
//       location: "Andaman",
//       country: "India",
//     },
//     {
//       title: "Riverside Chalet",
//       description: "A charming chalet by the river.",
//       image: "https://images.unsplash.com/photo-1566226462-bd302922a9fa?auto=format&fit=crop&w=800&q=60",
//       price: 2300,
//       location: "Darjeeling",
//       country: "India",
//     },
//     {
//       title: "Luxury Villa",
//       description: "Spacious villa with premium amenities.",
//       image: "https://images.unsplash.com/photo-1520917781784-26438ffb6994?auto=format&fit=crop&w=800&q=60",
//       price: 5000,
//       location: "Chennai",
//       country: "India",
//     },
//     {
//       title: "Beachfront Apartment",
//       description: "Stylish apartment with beach views.",
//       image: "https://images.unsplash.com/photo-1562164580-6f300b320177?auto=format&fit=crop&w=800&q=60",
//       price: 3500,
//       location: "Pune",
//       country: "India",
//     },
//     {
//       title: "Snowy Chalet",
//       description: "Cozy chalet in a snowy mountain region.",
//       image: "https://images.unsplash.com/photo-1603020212676-d16b3b1fa3a1?auto=format&fit=crop&w=800&q=60",
//       price: 2700,
//       location: "Kashmir",
//       country: "India",
//     },
//     {
//       title: "City Escape Loft",
//       description: "Chic loft for a quick city escape.",
//       image: "https://images.unsplash.com/photo-1618360772573-bc24d82c95f7?auto=format&fit=crop&w=800&q=60",
//       price: 2500,
//       location: "Hyderabad",
//       country: "India",
//     },
//     {
//       title: "Desert Oasis",
//       description: "A peaceful oasis in the desert.",
//       image: "https://images.unsplash.com/photo-1505816917-6fd1f937b2a3?auto=format&fit=crop&w=800&q=60",
//       price: 3200,
//       location: "Jaisalmer",
//       country: "India",
//     },
//     //bhola

//     {
//       title: "Beachside Villa",
//       description: "A beautiful villa near the beach.",
//       image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
//       price: 3000,
//       location: "Goa",
//       country: "India",
//   },
//   {
//       title: "Mountain Cabin",
//       description: "Peaceful place in the hills.",
//       image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
//       price: 1500,
//       location: "Manali",
//       country: "India",
//   },
//   {
//       title: "Luxury Villa",
//       description: "A luxurious villa with a private pool.",
//       image: "https://images.unsplash.com/photo-1590490360183-8b0b7f4d9b9b?auto=format&fit=crop&w=800&q=60",
//       price: 5000,
//       location: "Maldives",
//       country: "Maldives",
//   },
//   {
//       title: "Rustic Cabin",
//       description: "A cozy cabin in the woods.",
//       image: "https://images.unsplash.com/photo-1519817650390-64a93db511aa?auto=format&fit=crop&w=800&q=60",
//       price: 1200,
//       location: "Shimla",
//       country: "India",
//   },
//   {
//       title: "Modern Apartment",
//       description: "A stylish apartment in the city center.",
//       image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
//       price: 2000,
//       location: "Mumbai",
//       country: "India",
//   },
//   {
//       title: "Seaside Cottage",
//       description: "A charming cottage by the sea.",
//       image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
//       price: 1800,
//       location: "Kerala",
//       country: "India",
//   },
//   {
//       title: "Hilltop Retreat",
//       description: "A serene retreat on a hilltop.",
//       image: "https://images.unsplash.com/photo-1519817650390-64a93db511aa?auto=format&fit=crop&w=800&q=60",
//       price: 2500,
//       location: "Darjeeling",
//       country: "India",
//   },
//   {
//       title: "Beachfront Bungalow",
//       description: "A bungalow with direct beach access.",
//       image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
//       price: 3500,
//       location: "Goa",
//       country: "India",
//   },
//   {
//       title: "Lakeview Cabin",
//       description: "A cabin with stunning lake views.",
//       image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
//       price: 2200,
//       location: "Nainital",
//       country: "India",
//   },
//   {
//       title: "Desert Oasis",
//       description: "A luxurious stay in the desert.",
//       image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
//       price: 4000,
//       location: "Jaisalmer",
//       country: "India",
//   },
//   {
//       title: "Jungle Treehouse",
//       description: "A unique stay in a jungle treehouse.",
//       image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
//       price: 3000,
//       location: "Wayanad",
//       country: "India",
//   },
//   {
//       title: "Snowy Chalet",
//       description: "A cozy chalet in the snow.",
//       image: "https://images.unsplash.com/photo-1519817650390-64a93db511aa?auto=format&fit=crop&w=800&q=60",
//       price: 4500,
//       location: "Gulmarg",
//       country: "India",
//   },
//   {
//       title: "Urban Loft",
//       description: "A modern loft in the heart of the city.",
//       image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
//       price: 2500,
//       location: "Delhi",
//       country: "India",
//   },
//   {
//       title: "Island Villa",
//       description: "A private villa on an island.",
//       image: "https://images.unsplash.com/photo-1590490360183-8b0b7f4d9b9b?auto=format&fit=crop&w=800&q=60",
//       price: 6000,
//       location: "Andaman",
//       country: "India",
//   },
//   {
//       title: "Countryside Cottage",
//       description: "A peaceful cottage in the countryside.",
//       image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
//       price: 1700,
//       location: "Coorg",
//       country: "India",
//   },
//   {
//       title: "Luxury Penthouse",
//       description: "A penthouse with panoramic city views.",
//       image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
//       price: 8000,
//       location: "Bangalore",
//       country: "India",
//   },
//   {
//       title: "Forest Cabin",
//       description: "A secluded cabin in the forest.",
//       image: "https://images.unsplash.com/photo-1519817650390-64a93db511aa?auto=format&fit=crop&w=800&q=60",
//       price: 2000,
//       location: "Munnar",
//       country: "India",
//   },
//   {
//       title: "Cliffside Villa",
//       description: "A villa perched on a cliff.",
//       image: "https://images.unsplash.com/photo-1590490360183-8b0b7f4d9b9b?auto=format&fit=crop&w=800&q=60",
//       price: 5500,
//       location: "Vizag",
//       country: "India",
//   },
//   {
//       title: "Heritage Haveli",
//       description: "A royal stay in a heritage haveli.",
//       image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
//       price: 3000,
//       location: "Jaipur",
//       country: "India",
//   },
//   {
//       title: "Riverfront Cottage",
//       description: "A cottage by the river.",
//       image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
//       price: 1800,
//       location: "Rishikesh",
//       country: "India",
//   },

//   ];


module.exports.data = [
  {
    title: "Beachside Villa",
    description: "A beautiful villa near the beach.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Goa",
    country: "India",
  },
  {
    title: "Mountain Cabin",
    description: "Peaceful place in the hills.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Manali",
    country: "India",
  },
  {
    title: "Luxury Villa",
    description: "A luxurious villa with a private pool.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Rustic Cabin",
    description: "A cozy cabin in the woods.",
    image:"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Modern Apartment",
    description: "A stylish apartment in the city center.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Seaside Cottage",
    description: "A charming cottage by the sea.",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Kerala",
    country: "India",
  },
  {
    title: "Hilltop Retreat",
    description: "A serene retreat on a hilltop.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Beachfront Bungalow",
    description: "A bungalow with direct beach access.",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Lakeview Cabin",
    description: "A cabin with stunning lake views.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Desert Oasis",
    description: "A luxurious stay in the desert.",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Jungle Treehouse",
    description: "A unique stay in a jungle treehouse.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Snowy Chalet",
    description: "A cozy chalet in the snow.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Gulmarg",
    country: "India",
  },
  {
    title: "Urban Loft",
    description: "A modern loft in the heart of the city.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Island Villa",
    description: "A private villa on an island.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 6000,
    location: "Andaman",
    country: "India",
  },
  {
    title: "Countryside Cottage",
    description: "A peaceful cottage in the countryside.",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "A penthouse with panoramic city views.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
    price: 8000,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Forest Cabin",
    description: "A secluded cabin in the forest.",
    image:"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Cliffside Villa",
    description: "A villa perched on a cliff.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 5500,
    location: "Vizag",
    country: "India",
  },
  {
    title: "Heritage Haveli",
    description: "A royal stay in a heritage haveli.",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Riverfront Cottage",
    description: "A cottage by the river.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Rishikesh",
    country: "India",
  },
];

 

